name: Issue Triage Helper
on:
  issues:
    types: [labeled]
jobs:
  routed:
    runs-on: ubuntu-latest
    if: >-
      contains(
        fromJSON('[
          "Status: In Progress",
          "Status: Backlog",
          "Status: Needs More Information"
        ]'),
        github.event.label.name
      )
    steps:
      - name: "Remove all 'Status: *' labels"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: |
          labels_to_remove=$(jq -r '[.issue.labels[].name | select(startswith("Status: ") and . != "${{ github.event.label.name }}")] | join(",")' $GITHUB_EVENT_PATH)
          if [[ -n "${labels_to_remove// /}" ]]; then
            # Use `--add-label` to ensure consistent state as this action may run with race conditons
            gh issue edit ${{ github.event.issue.number }} --remove-label "$labels_to_remove" --add-label "${{ github.event.label.name }}"
          fi