name: Unroute new issue - test
on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.PAT }}
jobs:
  case_1:
    name: "It skips unrouting for Sentry org members."
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup
        name: setup
        run: .github/workflows/test-helpers/make-issue "This is an issue, clearly."
      - name: test
        run: |
          set -x
          grep "Status: Unrouted" issue-labels || true
  case_2:
    name: "It labels new issues with `Status: Unrouted`."
    needs: case_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: setup
        name: setup
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_NONMEMBER }}
        run: |
          .github/workflows/test-helpers/make-issue "Why u no work?"
      - name: test
        run: |
          set -x
          grep "Status: Unrouted" issue-labels
